name: native_updater
description: Flutter package for prompting users to update with a native dialog whether using the app store version or any version at the user's discretion.
author: Ofload <tech@ofload.com>

version: 0.1.1
homepage: https://github.com/ofload/native_updater

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # package_info will help us to find current installed version of application.
  package_info: ^2.0.2
  # url_launcher will help us to trigger app store / play store url from our app.
  url_launcher: ^6.0.10
  # Enables In App Updates on Android using the official Android APIs.
  in_app_update: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/native_updater/images/google_play.png
